# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ncc.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        self.tabWidget.setObjectName("tabWidget")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.homeTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 1, 0, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 2, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.homeTab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.homeTab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_7.addWidget(self.pushButton_4, 3, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 1, 4, 3, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem4, 0, 0, 1, 5)
        self.pushButton_2 = QtWidgets.QPushButton(self.homeTab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_7.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.homeTab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_7.addWidget(self.pushButton_3, 1, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 1, 2, 3, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 4, 0, 1, 5)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.homeTab, "")
        self.kernelTab = QtWidgets.QWidget()
        self.kernelTab.setObjectName("kernelTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.kernelTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stableKernelRepositoryLabel = QtWidgets.QLabel(self.kernelTab)
        self.stableKernelRepositoryLabel.setObjectName("stableKernelRepositoryLabel")
        self.gridLayout_3.addWidget(self.stableKernelRepositoryLabel, 3, 1, 1, 1)
        self.ltsKernelBtn = QtWidgets.QPushButton(self.kernelTab)
        self.ltsKernelBtn.setObjectName("ltsKernelBtn")
        self.gridLayout_3.addWidget(self.ltsKernelBtn, 7, 1, 1, 1)
        self.stableKernelSystemLabel = QtWidgets.QLabel(self.kernelTab)
        self.stableKernelSystemLabel.setObjectName("stableKernelSystemLabel")
        self.gridLayout_3.addWidget(self.stableKernelSystemLabel, 2, 1, 1, 1)
        self.ltsKernelRepositoryLabel = QtWidgets.QLabel(self.kernelTab)
        self.ltsKernelRepositoryLabel.setObjectName("ltsKernelRepositoryLabel")
        self.gridLayout_3.addWidget(self.ltsKernelRepositoryLabel, 6, 1, 1, 1)
        self.stableKernelBtn = QtWidgets.QPushButton(self.kernelTab)
        self.stableKernelBtn.setObjectName("stableKernelBtn")
        self.gridLayout_3.addWidget(self.stableKernelBtn, 4, 1, 1, 1)
        self.ltsKernelSystemLabel = QtWidgets.QLabel(self.kernelTab)
        self.ltsKernelSystemLabel.setObjectName("ltsKernelSystemLabel")
        self.gridLayout_3.addWidget(self.ltsKernelSystemLabel, 5, 1, 1, 1)
        self.hardenedKernelLabel = QtWidgets.QLabel(self.kernelTab)
        self.hardenedKernelLabel.setObjectName("hardenedKernelLabel")
        self.gridLayout_3.addWidget(self.hardenedKernelLabel, 8, 0, 3, 1)
        self.hardenedKernelBtn = QtWidgets.QPushButton(self.kernelTab)
        self.hardenedKernelBtn.setObjectName("hardenedKernelBtn")
        self.gridLayout_3.addWidget(self.hardenedKernelBtn, 10, 1, 1, 1)
        self.zenKernelSystemLabel = QtWidgets.QLabel(self.kernelTab)
        self.zenKernelSystemLabel.setObjectName("zenKernelSystemLabel")
        self.gridLayout_3.addWidget(self.zenKernelSystemLabel, 11, 1, 1, 1)
        self.ltsKernelLabel = QtWidgets.QLabel(self.kernelTab)
        self.ltsKernelLabel.setObjectName("ltsKernelLabel")
        self.gridLayout_3.addWidget(self.ltsKernelLabel, 5, 0, 3, 1)
        self.zenKernelBtn = QtWidgets.QPushButton(self.kernelTab)
        self.zenKernelBtn.setObjectName("zenKernelBtn")
        self.gridLayout_3.addWidget(self.zenKernelBtn, 13, 1, 1, 1)
        self.hardenedKernelRepositoryLabel = QtWidgets.QLabel(self.kernelTab)
        self.hardenedKernelRepositoryLabel.setObjectName("hardenedKernelRepositoryLabel")
        self.gridLayout_3.addWidget(self.hardenedKernelRepositoryLabel, 9, 1, 1, 1)
        self.stableKernelLabel = QtWidgets.QLabel(self.kernelTab)
        self.stableKernelLabel.setObjectName("stableKernelLabel")
        self.gridLayout_3.addWidget(self.stableKernelLabel, 2, 0, 3, 1)
        self.hardenedKernelSystemLabel = QtWidgets.QLabel(self.kernelTab)
        self.hardenedKernelSystemLabel.setObjectName("hardenedKernelSystemLabel")
        self.gridLayout_3.addWidget(self.hardenedKernelSystemLabel, 8, 1, 1, 1)
        self.zenKernelRepositoryLabel = QtWidgets.QLabel(self.kernelTab)
        self.zenKernelRepositoryLabel.setObjectName("zenKernelRepositoryLabel")
        self.gridLayout_3.addWidget(self.zenKernelRepositoryLabel, 12, 1, 1, 1)
        self.zenKernelLabel = QtWidgets.QLabel(self.kernelTab)
        self.zenKernelLabel.setObjectName("zenKernelLabel")
        self.gridLayout_3.addWidget(self.zenKernelLabel, 11, 0, 3, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.kernelTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.LogPage = QtWidgets.QWidget()
        self.LogPage.setObjectName("LogPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.LogPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.exitLog = QtWidgets.QPushButton(self.LogPage)
        self.exitLog.setObjectName("exitLog")
        self.gridLayout_6.addWidget(self.exitLog, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 1, 0, 1, 1)
        self.logText = QtWidgets.QTextBrowser(self.LogPage)
        self.logText.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.logText.setObjectName("logText")
        self.gridLayout_6.addWidget(self.logText, 0, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.LogPage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Namib Control Center"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homeTab), _translate("MainWindow", "Home"))
        self.stableKernelRepositoryLabel.setText(_translate("MainWindow", "linux"))
        self.ltsKernelBtn.setText(_translate("MainWindow", "linuxlts"))
        self.stableKernelSystemLabel.setText(_translate("MainWindow", "linux"))
        self.ltsKernelRepositoryLabel.setText(_translate("MainWindow", "linuxlts"))
        self.stableKernelBtn.setText(_translate("MainWindow", "linux"))
        self.ltsKernelSystemLabel.setText(_translate("MainWindow", "linuxlts"))
        self.hardenedKernelLabel.setText(_translate("MainWindow", "Linux Hardened"))
        self.hardenedKernelBtn.setText(_translate("MainWindow", "linuxhardened"))
        self.zenKernelSystemLabel.setText(_translate("MainWindow", "linuxzen"))
        self.ltsKernelLabel.setText(_translate("MainWindow", "Linux LTS"))
        self.zenKernelBtn.setText(_translate("MainWindow", "linuxzen"))
        self.hardenedKernelRepositoryLabel.setText(_translate("MainWindow", "linuxhardened"))
        self.stableKernelLabel.setText(_translate("MainWindow", "Linux"))
        self.hardenedKernelSystemLabel.setText(_translate("MainWindow", "linuxhardened"))
        self.zenKernelRepositoryLabel.setText(_translate("MainWindow", "linuxzen"))
        self.zenKernelLabel.setText(_translate("MainWindow", "Linux Zen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kernelTab), _translate("MainWindow", "Kernels"))
        self.exitLog.setText(_translate("MainWindow", "Go back"))
